version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - /home/mdx/github/prometheus-Grafana/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    networks:
      - monitor

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - monitor

  jenkins:
    image: jenkins/jenkins
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped
    networks:
      - monitor

  gitlab:
    image: gitlab/gitlab-ce:13.9.2-ce.0
    container_name: gitlab
    hostname: example.com
    ports:
      - "443:443"
      - "80:80"
      - "2222:22"
    volumes:
      - ${GITLAB_HOME}/config:/etc/gitlab
      - ${GITLAB_HOME}/logs:/var/log/gitlab
      - ${GITLAB_HOME}/data:/var/opt/gitlab
    environment:
      GITLAB_ROOT_EMAIL: "root@local"
      GITLAB_ROOT_PASSWORD: "P@ssw0rd"
      EXTERNAL_URL: "http://example.com"
    restart: unless-stopped
    networks:
      - monitor
 

volumes:
  jenkins_home:

networks:
  monitor:
    driver: bridge
