---
global:
  scrape_interval: 15s

scrape_configs:
  # 1. Prometheus itself (Internal Monitoring)
  - job_name: 'prometheus'
    # Targets are defined relative to the Prometheus container (localhost:9090)
    static_configs:
      - targets: ['localhost:9090']

  # 2. GitLab (Uses IP, but service name 'gitlab:80' is recommended if in the same network)
  - job_name: 'gitlab'
    metrics_path: '/-/metrics'
    static_configs:
      - targets: ['172.20.0.6:80'] # Changed to use service name for robustness

  # 3. Jenkins (CI/CD Master)
  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['jenkins:8080']
    # NOTE: scrape_interval is inherited from global (15s), so it's removed here.

  # 4. Nexus Repository Manager 3
  - job_name: 'nexus3'
    static_configs:
      - targets: ['172.20.0.3:8081']
    metrics_path: '/service/metrics/prometheus'
    # IMPORTANT: Replace the placeholder password below.
    basic_auth:
      username: 'admin'
      password: 'P@ssw0rd@1' 

  # 5. SonarQube (System Metrics)
  - job_name: 'sonarqube'
    static_configs:
      - targets: ['172.20.0.7:9000']
    metrics_path: '/api/monitoring/metrics'
    # IMPORTANT: Replace the placeholder password below.
    basic_auth:
      username: 'admin'
      password: 'P@ssw0rd@1'