---
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: gitlab
    scrape_interval: 15s
    metrics_path: /-/metrics
    static_configs:
      - targets:
          - gitlab:80
  - job_name: jenkins
    metrics_path: /prometheus
    static_configs:
      - targets:
          - jenkins:8080
