global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Grafana
  - job_name: 'gitlab'
    static_configs:
      - targets: ['172.17.0.2:80']
 
